- name: Checkmarx AST Github Action
  uses: Checkmarx/ast-github-action@2.0.23
  with:
    base_uri: https://marketaxess.checkmarx.com
    cx_tenant: ${{ secrets.cx_tenant }}
    cx_client_id: ${{ secrets.cx_client_id }}
    cx_client_secret: ${{ secrets.cx_client_secret }}
