name: Checkmarx AST Scan

on:
  push:
    branches:
      - main
jobs:
  checkmarx_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          base_uri: https://us.ast.checkmarx.net
          cx_tenant: marketaxess
          cx_client_id: ${{ secrets.cx_client_id }}
          cx_client_secret: ${{ secrets.cx_client_secret }}
